//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAT_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int PK_AccountId { get; set; }
        public int FK_AccountAccessLevel { get; set; }
        public string UQ_AccountLogin { get; set; }
        public string AccountPass { get; set; }
        public string AccountIpAddress { get; set; }
        public Nullable<System.DateTime> AccountLastEnter { get; set; }
    
        public virtual AccessLevel tbAccessLevel { get; set; }
    }
}
