//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAT_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analyzer
    {
        public int PK_AnalyzerId { get; set; }
        public Nullable<int> FK_AnalyzerUser { get; set; }
        public Nullable<System.DateTime> AnalyzerAnalyseStarted { get; set; }
        public byte[] AnalyzerAnalyseEnded { get; set; }
        public int FK_AnalyzerOrderId { get; set; }
    
        public virtual Employe tbEmploye { get; set; }
        public virtual Order tbOrder { get; set; }
    }
}
