//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAT_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.tbOrders = new HashSet<Order>();
        }
    
        public int PK_ClientPassport { get; set; }
        public int FK_AccessLevel { get; set; }
        public string ClientFullName { get; set; }
        public Nullable<System.DateTime> ClientDateOfBirth { get; set; }
        public string ClientPhoneNumber { get; set; }
        public string ClientEmail { get; set; }
        public Nullable<int> UQ_ClientInsurancePolicyNumb { get; set; }
        public string ClientInsurancePolicyType { get; set; }
        public string FK_ClientInsuranceCompany { get; set; }
    
        public virtual AccessLevel tbAccessLevel { get; set; }
        public virtual InsuranceСompanies tbInsuranceСompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> tbOrders { get; set; }
    }
}
