//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAT_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.tbAnalyzers = new HashSet<Analyzer>();
            this.tbFinancialDeps = new HashSet<FinancialDep>();
        }
    
        public int PK_EmployeeId { get; set; }
        public string EmployeeFullName { get; set; }
        public Nullable<int> FK_EmployeeAccessLevel { get; set; }
        public string EmployeeServiceCode { get; set; }
        public byte[] EmployeePhoto { get; set; }
    
        public virtual AccessLevel tbAccessLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analyzer> tbAnalyzers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialDep> tbFinancialDeps { get; set; }
    }
}
