//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAT_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialDep
    {
        public int PK_FinancialRept { get; set; }
        public int FK_EmployeeId { get; set; }
        public string FK_CompanyName { get; set; }
        public string ReportDetails { get; set; }
        public Nullable<double> SummaryBill { get; set; }
        public Nullable<System.DateTime> FinancialReptDate { get; set; }
    
        public virtual Employe tbEmploye { get; set; }
        public virtual InsuranceСompanies tbInsuranceСompanies { get; set; }
    }
}
